site_name: My Docs
nav:
  - "引言": index.md
  - "算法": algorithm_basic.md
  - "微服务": microservices.md
  - "性能测试": performance-test.md
  - "Markdown语法": markdown.md
#theme:
##name: 'readthedocs'
#name: material
##name: mkdocs
theme:
    name: "material"
#    logo:
#        icon: "mkdocs"
    palette:
        primary: "black"
        accent: "deep orange"
    language: "zh"
copyright:

  <br></br>Copyright @sjia | Jesus loves me</a>

